### ISSUE TITLE
似乎不支持fix-gro参数

### ISSUE THREAD

**Issue by void285** [sensec/luci-app-udp2raw#8]
用了最新版 https://github.com/wangyu-/udp2raw-tunnel/releases/tag/20190716.test.0

服务器开启fix-gro参数时，客户端无法连接。将`--fix-gro`写入`/var/etc/udp2raw.default.conf`不起作用，会被覆写。

**Comment by void285** [comment]
修改了下启动脚本就好了，先用着，也许以后luci中可以添加勾选项。

`vim /etc/init.d/udp2raw`，添加了第2行：
```
        echo "--disable-color" >> $config_file
        echo "--fix-gro" >> $config_file
```

**Comment by sxml** [comment]
> 修改了下启动脚本就好了，先用着，也许以后luci中可以添加勾选项。
> 
> `vim /etc/init.d/udp2raw`，添加了第2行：
> 
> ```
>         echo "--disable-color" >> $config_file
>         echo "--fix-gro" >> $config_file
> ```

客服端 没--fix-gro 选项 这代码添加那个位置 ？随便底部可以吗
